package postgres

import (
	"context"
	"testing"
	"time"

	"github.com/rudimk/replicare/internal/engine"
)

// TestReseedSequencesIntegration exercises engine.SequenceReseeder against the real
// harness target. It reproduces the DR gap — rows present with ids ahead of an
// un-advanced identity/serial sequence (as replicated rows land via explicit-id inserts,
// which never call nextval) — then proves ReseedSequences advances the counter to
// max(id)+1 so the next DB-generated id does not collide. It also proves dry-run writes
// nothing, and that a UUID/natural PK (no owned sequence) is skipped.
func TestReseedSequencesIntegration(t *testing.T) {
	cc := harnessConn(t, "target") // skips unless REPLICARE_INTEGRATION=1
	ctx, cancel := context.WithTimeout(context.Background(), 40*time.Second)
	defer cancel()

	tgt := &Sink{cfg: cc}
	if err := tgt.Connect(ctx); err != nil {
		t.Fatalf("connect target: %v", err)
	}
	t.Cleanup(func() { _ = tgt.Close(context.Background()) })
	t.Cleanup(func() { _, _ = tgt.conn.Exec(context.Background(), "DROP SCHEMA IF EXISTS rc_it_rs CASCADE") })

	mustExec := func(sql string) {
		t.Helper()
		if _, err := tgt.conn.Exec(ctx, sql); err != nil {
			t.Fatalf("exec %q: %v", sql, err)
		}
	}

	mustExec("DROP SCHEMA IF EXISTS rc_it_rs CASCADE")
	mustExec("CREATE SCHEMA rc_it_rs")

	// identity PK, serial column, and a UUID (no owned sequence) — explicit-id inserts
	// mimic replicated rows and leave every sequence un-advanced.
	mustExec(`CREATE TABLE rc_it_rs.ident (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text)`)
	mustExec(`INSERT INTO rc_it_rs.ident (id, v) VALUES (1,'a'),(2,'b'),(100,'c')`)
	mustExec(`CREATE TABLE rc_it_rs.ser (id serial PRIMARY KEY, v text)`)
	mustExec(`INSERT INTO rc_it_rs.ser (id, v) VALUES (1,'a'),(50,'b')`)
	mustExec(`CREATE TABLE rc_it_rs.uid (id uuid PRIMARY KEY, v text)`)
	mustExec(`INSERT INTO rc_it_rs.uid VALUES (md5(random()::text)::uuid, 'a')`)

	identRef := engine.TableRef{Schema: "rc_it_rs", Name: "ident"}

	// Sequence last_value before any reseed (un-advanced: an explicit-id insert never
	// called nextval).
	seqLast := func() int64 {
		t.Helper()
		var lv int64 // pg_sequences.last_value is NULL until the sequence is read/set
		if err := tgt.conn.QueryRow(ctx,
			`SELECT COALESCE(last_value, 0) FROM pg_sequences WHERE schemaname='rc_it_rs' AND sequencename='ident_id_seq'`).Scan(&lv); err != nil {
			t.Fatalf("read seq last_value: %v", err)
		}
		return lv
	}
	before := seqLast()

	// Dry-run: reports max+1 but must not write.
	dr, err := tgt.ReseedSequences(ctx, identRef, true)
	if err != nil {
		t.Fatalf("dry-run reseed: %v", err)
	}
	if len(dr.Columns) != 1 || dr.Columns[0].Column != "id" || dr.Columns[0].Max != 100 || dr.Columns[0].SetTo != 101 {
		t.Fatalf("dry-run result = %+v, want one col id max=100 setTo=101", dr.Columns)
	}
	if after := seqLast(); after != before {
		t.Fatalf("dry-run changed the sequence (%d -> %d)", before, after)
	}

	// Real reseed, then a DB-generated insert must land at 101 (no collision with id=100).
	rr, err := tgt.ReseedSequences(ctx, identRef, false)
	if err != nil {
		t.Fatalf("reseed: %v", err)
	}
	if len(rr.Columns) != 1 || rr.Columns[0].SetTo != 101 {
		t.Fatalf("reseed result = %+v, want setTo=101", rr.Columns)
	}
	var newID int64
	if err := tgt.conn.QueryRow(ctx, `INSERT INTO rc_it_rs.ident (v) VALUES ('d') RETURNING id`).Scan(&newID); err != nil {
		t.Fatalf("post-reseed insert: %v", err)
	}
	if newID != 101 {
		t.Fatalf("post-reseed DB-generated id = %d, want 101", newID)
	}

	// serial column: same behavior.
	serRes, err := tgt.ReseedSequences(ctx, engine.TableRef{Schema: "rc_it_rs", Name: "ser"}, false)
	if err != nil {
		t.Fatalf("reseed ser: %v", err)
	}
	if len(serRes.Columns) != 1 || serRes.Columns[0].Max != 50 || serRes.Columns[0].SetTo != 51 {
		t.Fatalf("ser reseed = %+v, want max=50 setTo=51", serRes.Columns)
	}
	var serID int64
	if err := tgt.conn.QueryRow(ctx, `INSERT INTO rc_it_rs.ser (v) VALUES ('c') RETURNING id`).Scan(&serID); err != nil {
		t.Fatalf("post-reseed ser insert: %v", err)
	}
	if serID != 51 {
		t.Fatalf("post-reseed ser id = %d, want 51", serID)
	}

	// UUID PK: no owned sequence -> skipped (empty Columns, no error).
	uidRes, err := tgt.ReseedSequences(ctx, engine.TableRef{Schema: "rc_it_rs", Name: "uid"}, false)
	if err != nil {
		t.Fatalf("reseed uid: %v", err)
	}
	if len(uidRes.Columns) != 0 {
		t.Fatalf("uuid table should have no owned sequence, got %+v", uidRes.Columns)
	}
}
