{{- if and (not .Values.secret.existingSecret) .Values.secret.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "replicare.fullname" . }}
  labels:
    {{- include "replicare.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
