apiVersion: v1
kind: Service
metadata:
  name: {{ include "replicare.fullname" . }}
  labels:
    {{- include "replicare.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "replicare.selectorLabels" . | nindent 4 }}
  ports:
    - name: status
      port: {{ .Values.service.ports.status }}
      targetPort: status
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
