package main

// The load-test schema lives in its own `loadgen` schema so it never collides
// with anything else on the server and can be selected wholesale by replicare
// (include: ["loadgen.*"]).
//
// The 10 tables are chosen to exercise replicare's hard paths, not just to hold
// data:
//
//   - tenants          hub table many others FK to (giant-component pressure);
//     identity PK, jsonb, text[], timestamptz, bool.
//   - categories       self-referential hierarchy column (self-ref FK under --cyclic).
//   - users            bytea, inet, numeric, date, jsonb, many nullable columns;
//     primary_order_id closes a users<->orders cycle under --cyclic.
//   - products         COMPOSITE text PK (tenant_id, sku); float8[]; timestamp
//     WITHOUT time zone; the target of PK-changing updates.
//   - orders           UUID PK; char(3); nullable FK to users.
//   - order_items      composite PK; composite FK to products ON UPDATE CASCADE
//     (so a SKU rename is a PK change that cascades to children).
//   - product_categories  M:N join, composite PK, two FKs.
//   - events           the high-volume table (~1M rows); wide type coverage.
//   - generated_metrics   GENERATED ... STORED column + identity PK.
//   - audit_log        NO primary key / no unique key -> replicare skips it with
//     a loud warning. verify() excludes it for the same reason.
//
// The default schema is ACYCLIC. The optional --cyclic flag adds two nullable FK
// cycles (cyclicDDL) to exercise replicare's cyclic-copy AND cyclic-streaming
// paths; both converge under churn with standard non-DEFERRABLE FKs (see the note
// on cyclicDDL).
//
// All DDL is idempotent (CREATE ... IF NOT EXISTS; cyclicDDL guards ADD CONSTRAINT
// on duplicate_object). It is applied to BOTH the source and, via `loadgen ddl`,
// the target -- replicare replicates data only, so the target tables must pre-exist.
var ddlStatements = []string{
	`CREATE SCHEMA IF NOT EXISTS loadgen`,

	`CREATE TABLE IF NOT EXISTS loadgen.tenants (
		id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name       text NOT NULL,
		plan       varchar(20) NOT NULL,
		config     jsonb NOT NULL DEFAULT '{}'::jsonb,
		tags       text[] NOT NULL DEFAULT '{}',
		created_at timestamptz NOT NULL DEFAULT now(),
		active     boolean NOT NULL DEFAULT true
	)`,

	// parent_id is a self-referential hierarchy column. The self-ref FK is added
	// only under --cyclic (see cyclicDDL): replicare's pre-flight classifies a
	// nullable self-ref as null_then_fill, but its initial copy does not converge a
	// cyclic component that has downstream children, so the default schema keeps the
	// column without the constraint.
	`CREATE TABLE IF NOT EXISTS loadgen.categories (
		id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		tenant_id bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		parent_id bigint,
		name      text NOT NULL,
		depth     smallint NOT NULL DEFAULT 0
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.users (
		id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		tenant_id        bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		email            text NOT NULL,
		full_name        text,
		balance          numeric(20,4) NOT NULL DEFAULT 0,
		prefs            jsonb NOT NULL DEFAULT '{}'::jsonb,
		avatar           bytea,
		last_ip          inet,
		signup_date      date NOT NULL DEFAULT current_date,
		last_login       timestamptz,
		primary_order_id uuid,
		is_active        boolean NOT NULL DEFAULT true,
		UNIQUE (tenant_id, email)
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.products (
		tenant_id  bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		sku        text NOT NULL,
		name       text NOT NULL,
		price      numeric(12,2) NOT NULL,
		dims       double precision[] NOT NULL DEFAULT '{}',
		attrs      jsonb NOT NULL DEFAULT '{}'::jsonb,
		weight_g   integer,
		created_at timestamp NOT NULL DEFAULT now(),
		PRIMARY KEY (tenant_id, sku)
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.orders (
		id        uuid PRIMARY KEY,
		tenant_id bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		-- Nullable FK to users. In the default (acyclic) schema this is a plain
		-- child->parent edge (users copied before orders). users.primary_order_id
		-- closes a users<->orders cycle only under --cyclic (cyclicDDL).
		user_id   bigint REFERENCES loadgen.users(id) ON DELETE CASCADE,
		status    text NOT NULL,
		total     numeric(14,2) NOT NULL,
		currency  char(3) NOT NULL DEFAULT 'USD',
		placed_at timestamptz NOT NULL DEFAULT now(),
		ship_by   date,
		notes     text,
		metadata  jsonb NOT NULL DEFAULT '{}'::jsonb
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.order_items (
		order_id   uuid NOT NULL REFERENCES loadgen.orders(id) ON DELETE CASCADE,
		line_no    integer NOT NULL,
		tenant_id  bigint NOT NULL,
		sku        text NOT NULL,
		qty        integer NOT NULL,
		unit_price numeric(12,2) NOT NULL,
		discount   numeric(5,2),
		PRIMARY KEY (order_id, line_no),
		FOREIGN KEY (tenant_id, sku)
			REFERENCES loadgen.products(tenant_id, sku) ON UPDATE CASCADE ON DELETE CASCADE
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.product_categories (
		tenant_id   bigint NOT NULL,
		sku         text NOT NULL,
		category_id bigint NOT NULL REFERENCES loadgen.categories(id) ON DELETE CASCADE,
		added_at    timestamptz NOT NULL DEFAULT now(),
		PRIMARY KEY (tenant_id, sku, category_id),
		FOREIGN KEY (tenant_id, sku)
			REFERENCES loadgen.products(tenant_id, sku) ON UPDATE CASCADE ON DELETE CASCADE
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.events (
		id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		tenant_id   bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		event_type  text NOT NULL,
		session     uuid NOT NULL,
		amount      numeric(18,6),
		ratio       double precision,
		flags       integer NOT NULL DEFAULT 0,
		payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
		labels      text[] NOT NULL DEFAULT '{}',
		occurred_at timestamptz NOT NULL DEFAULT now()
	)`,

	`CREATE TABLE IF NOT EXISTS loadgen.generated_metrics (
		id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		tenant_id   bigint NOT NULL REFERENCES loadgen.tenants(id) ON DELETE CASCADE,
		raw_value   numeric(18,4) NOT NULL,
		doubled     numeric(18,4) GENERATED ALWAYS AS (raw_value * 2) STORED,
		label       text NOT NULL,
		computed_at timestamptz NOT NULL DEFAULT now()
	)`,

	// No PRIMARY KEY and no UNIQUE key on purpose: replicare must skip this table
	// with a loud warning (telemetry-surfaced). It stays source-only.
	`CREATE TABLE IF NOT EXISTS loadgen.audit_log (
		tenant_id bigint NOT NULL,
		action    text NOT NULL,
		actor     text,
		at        timestamptz NOT NULL DEFAULT now(),
		detail    jsonb NOT NULL DEFAULT '{}'::jsonb
	)`,
}

// cyclicDDL adds the two NULLABLE FK cycles, applied only under --cyclic. Both are
// the kind pre-flight classifies as null_then_fill (never the NOT-NULL
// non-deferrable kind it refuses). They are separated from the default schema so
// the acyclic default stays the simplest case. Under --cyclic both initial copy
// AND streaming converge with standard non-DEFERRABLE FKs: the copier loads cyclic
// FK columns NULL then fills them, and streaming applies each table's upsert /
// delete / cyclic-fill in its own committed transaction so parents advance
// across batches and the cycle is closed by a final fill phase. ADD CONSTRAINT
// has no IF NOT EXISTS, so each is guarded on duplicate_object.
var cyclicDDL = []string{
	// categories self-reference (parent_id -> categories.id).
	`DO $$
	BEGIN
		ALTER TABLE loadgen.categories
			ADD CONSTRAINT categories_parent_id_fkey
			FOREIGN KEY (parent_id) REFERENCES loadgen.categories(id) ON DELETE SET NULL;
	EXCEPTION WHEN duplicate_object THEN NULL;
	END $$`,
	// users <-> orders 2-table cycle (users.primary_order_id -> orders.id;
	// orders.user_id -> users.id already exists).
	`DO $$
	BEGIN
		ALTER TABLE loadgen.users
			ADD CONSTRAINT users_primary_order_fk
			FOREIGN KEY (primary_order_id) REFERENCES loadgen.orders(id) ON DELETE SET NULL;
	EXCEPTION WHEN duplicate_object THEN NULL;
	END $$`,
}

// table describes one replicated table for verify(). order is a deterministic
// ORDER BY over the key so the content checksum is stable on both sides.
type table struct {
	name  string // schema-qualified
	order string // ORDER BY expression (the key)
}

// replicatedTables are the tables replicare should converge on the target, in a
// stable order. audit_log is intentionally absent: it has no key, so replicare
// skips it and there is nothing to converge.
var replicatedTables = []table{
	{"loadgen.tenants", "id"},
	{"loadgen.categories", "id"},
	{"loadgen.users", "id"},
	{"loadgen.products", "tenant_id, sku"},
	{"loadgen.orders", "id"},
	{"loadgen.order_items", "order_id, line_no"},
	{"loadgen.product_categories", "tenant_id, sku, category_id"},
	{"loadgen.events", "id"},
	{"loadgen.generated_metrics", "id"},
}
