apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "replicare.fullname" . }}
  labels:
    {{- include "replicare.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.config | nindent 4 }}
